version: "3"

services:
  movie:
    build: ./movie
    ports:
      - "9001:8001"
  director:
    build: ./director
    ports:
      - "9002:8002"
  watchlist:
    build: ./watchlist
    ports:
      - "9003:8003"
    depends_on:
      - movie
      - director
  user:
    build: ./user
    ports:
      - "9004:8004"
    depends_on:
      - watchlist
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
#
# volumes:
#   db-data:
