coverage:
    pytest --cov=movie --cov-report=term-missing --cov-report=xml:coverage.xml tests/

coverage-int:
    @coverage_output=$(pytest --cov=movie --cov-report=term --disable-warnings tests/ | grep "TOTAL" | awk '{print $4}' | sed 's/%//'); \
    echo "$coverage_output";

makemigrations arg="":
    bash ./commands/makemigrations.sh {{ arg }}

migrate:
    bash ./commands/migrate.sh

populatedb:
    bash ./commands/populate_db.sh

revertmigration arg="":
    bash ./commands/revert_migration.sh {{ arg }}
