coverage:
    pytest --cov=myapp --cov-report=term-missing --cov-report=xml:coverage.xml tests/

coverage-int:
    @coverage_output=$(pytest --cov=myapp --cov-report=term --disable-warnings tests/ | tail -n 10 | grep -oP '\d+\.\d+(?=%)'); \
    echo "Coverage percentage: $coverage_output%"; \
    echo "Coverage number: $(echo $coverage_output | cut -d'.' -f1)" > coverage.txt

makemigrations arg="":
    bash ./commands/makemigrations.sh {{ arg }}

migrate:
    bash ./commands/migrate.sh

populatedb:
    bash ./commands/populate_db.sh

revertmigration arg="":
    bash ./commands/revert_migration.sh {{ arg }}
